# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Philippa Kavanagh - English Classes
email: philippa.kavanagh@cantab.net
description: > # this means to ignore newlines until "baseurl:"
  Pip's website.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://bradkav.net" # the base hostname & protocol for your site


author: Philippa Kavanagh

# Build settings
#markdown: kramdown
#markdown: CommonMarkGhPages

markdown: kramdown
kramdown:
  parse_block_html: true

theme: serif

#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "tables"]

gems:
  - jekyll-seo-tag